global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    monitor: kernelci-monitor

rule_files:
  - "django.rules"

scrape_configs:
  - job_name: 'kernelci-backend'
    static_configs:
      - targets: ['host.docker.internal:8001']
    metrics_path: '/metrics/'
    scrape_interval: 10s
  - job_name: 'kernelci-ingester'
    static_configs:
      - targets: ['host.docker.internal:8002']
    metrics_path: '/metrics/'
    scrape_interval: 1s
